# Generated by Django 5.2.15 on 2026-07-11 00:10

from django.db import migrations, models


LEGACY_PAYMENT_METHODS = (
    "card",
    "cash_on_delivery",
    "balance_mock",
)
NEW_DEFAULT_PAYMENT_METHOD = "bank_card_test"


def migrate_legacy_payment_methods(apps, schema_editor):
    """Map all legacy test payment values to the new bank-card test value."""
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(
        payment_method__in=LEGACY_PAYMENT_METHODS,
    ).update(payment_method=NEW_DEFAULT_PAYMENT_METHOD)


def restore_legacy_payment_methods(apps, schema_editor):
    """Use the old card value when rolling the migration back."""
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(
        payment_method=NEW_DEFAULT_PAYMENT_METHOD,
    ).update(payment_method="card")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_order_total_price_non_negative_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_legacy_payment_methods,
            restore_legacy_payment_methods,
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_card_test", "Банківська картка (тест)"),
                    ("crypto_trc20_test", "Криптовалюта TRC20 (тест)"),
                    ("google_pay_test", "Google Pay (тест)"),
                ],
                max_length=20,
            ),
        ),
    ]
