# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cover_url",
            field=models.URLField(blank=True),
        ),
    ]
