# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True),
        ),
    ]
